//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobiquitous2016App.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mobiquitous2016App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   #271e1a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorBlack800 {
            get {
                return ResourceManager.GetString("ColorBlack800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #1976D2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorBlue {
            get {
                return ResourceManager.GetString("ColorBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #388E3C に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorGreen {
            get {
                return ResourceManager.GetString("ColorGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #D32F2F に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorRed {
            get {
                return ResourceManager.GetString("ColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #FFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorWhite {
            get {
                return ResourceManager.GetString("ColorWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #FBC02D に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorYellow {
            get {
                return ResourceManager.GetString("ColorYellow", resourceCulture);
            }
        }
    }
}
